--- 
title: "Introduction to sars2pack"
author: 
  - Vincent J. Carey^[Harard Medical School, Channing Laboratory, Brigham and Women's Hospital]
  - Charles Morefield^[Arctan, Inc.]
  - John Mallery^[MIT Artificial Intelligence Laboratory]
  - Sean Davis^[National Cancer Institute, National Institutes of Health]
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Introduction}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    highlight: pygments
    number_sections: yes
    theme: united
    toc: yes
---

# Motivation

The COVID-19 pandemic is ongoing. The situation on the ground is
changing daily as captured by data reported around the world. The
[sars2pack] package aims to:

- Provide timely, computable, easily accessible data for research,
   policy-making, and educational purposes.
- Promote easy computational experimentation with COVID-19 data
- Serve as a source of documentation and education for available
   COVID-19 analysis and visualization approaches.
- House recipes for regularly updated data products such as
   spreadsheets and maps for use by non-R-savvy data consumers.
- Collect interesting data stories along with code as data science
   training resources for the many biomedical researchers who cannot
   currently perform experiments


## Origins of this package

John C. Mallery conveyed code of Charles Morefield to harvest COVID-19
time series data.  Vince Carey then started an R package/github repo
to manage the relevant code.  The package was named `sars2pack` in
hopes of avoiding name conflict with many other packages while
remaining descriptive and focused.
