---
title: "Exploring the COVID-19 pandemic using sars2pack"
author: "Sean Davis <seandavi@gmail.com> and Vincent J. Carey, stvjc at channing.harvard.edu"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Usage and Data Exploration}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    highlight: pygments
    number_sections: yes
    theme: united
    toc: yes
---

```{r setup,echo=FALSE,message=FALSE,warning=FALSE}
library(BiocStyle)
library(sars2pack)
library(dplyr)
library(ggplot2)
library(tibble)
library(lubridate)
library(DT)
```
# Getting started

## Installation

```{r eval=FALSE}
BiocManager::install('seandavi/sars2pack')
```

## Usage

```{r message=FALSE, warning=FALSE, eval=FALSE}
library(sars2pack)
# documentation is in the form of gitbook site
browseURL('https://seandavi.github.io/COVID19Book/')
```

Navigate to the [extended online book for
documentation](https://seandavi.github.io/COVID19Book/) for
documentation, workflows, and example use cases along with background
material.
