---
title: 'Phylogenetic data'
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output:
  rmarkdown::html_document:
    number_sections: false
    toc: false
link-citations: yes
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Phylogenetic data}
  %\VignetteEncoding{UTF-8}
---


# Phylogenetic data

```{r}
library(sars2pack)
library(ggplot2)
library(dplyr)
```


```{r}
ntr = cov_glue_newick_data()
plot(ntr)
```


```{r}
dat = cov_glue_lineage_data()
dat = dat %>%
    dplyr::mutate(lineage = sub('^([^.][.]?[^.]+).*', '\\1', lineage)) %>%
    dplyr::mutate(region = countrycode::countrycode(country,origin='country.name',
                                                    destination='region')) %>%
    dplyr::group_by(epiweek,lineage,region) %>% 
    dplyr::summarize(cases=n()) %>%
    dplyr::filter(!is.na(region)) %>%
    dplyr::ungroup()
head(dat)
```

```{r}
p = dat %>%
    ggplot(aes(x=epiweek,y=cases,fill=lineage)) +
    geom_bar(stat='identity', position='fill') +
    facet_wrap("region",ncol=2) +
    theme(legend.position='bottom')
p
```

## Notes

- https://nextstrain.org/help/general/how-to-read-a-tree

