# need library(devtools) to succeed first
> source_gist("https://gist.github.com/vjcitn/7e2bc07db7b1b1716ccde225177f830f")
Sourcing https://gist.githubusercontent.com/vjcitn/7e2bc07db7b1b1716ccde225177f830f/raw/5c1e9cc5302db38db9c196911c39afee3d2bb5b1/do_italy.R
SHA-1 hash of file is 86c4f87d11a8975d904736f0a148596765c401b1
0/0 packages newly attached/loaded, see sessionInfo() for details.
0/0 packages newly attached/loaded, see sessionInfo() for details.
0/0 packages newly attached/loaded, see sessionInfo() for details.
0/0 packages newly attached/loaded, see sessionInfo() for details.
Waiting for profiling to be done...
Reproduction number estimate using  Exponential Growth  method.
R :  1.860969[ 1.852957 , 1.869037 ]
